// Code generated by Kitex v0.9.1. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	auth "github.com/trashwbin/dymall/rpc_gen/kitex_gen/auth"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DeliverTokenByRPC": kitex.NewMethodInfo(
		deliverTokenByRPCHandler,
		newDeliverTokenByRPCArgs,
		newDeliverTokenByRPCResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VerifyTokenByRPC": kitex.NewMethodInfo(
		verifyTokenByRPCHandler,
		newVerifyTokenByRPCArgs,
		newVerifyTokenByRPCResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddPolicy": kitex.NewMethodInfo(
		addPolicyHandler,
		newAddPolicyArgs,
		newAddPolicyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RemovePolicy": kitex.NewMethodInfo(
		removePolicyHandler,
		newRemovePolicyArgs,
		newRemovePolicyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddRoleForUser": kitex.NewMethodInfo(
		addRoleForUserHandler,
		newAddRoleForUserArgs,
		newAddRoleForUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RemoveRoleForUser": kitex.NewMethodInfo(
		removeRoleForUserHandler,
		newRemoveRoleForUserArgs,
		newRemoveRoleForUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRolesForUser": kitex.NewMethodInfo(
		getRolesForUserHandler,
		newGetRolesForUserArgs,
		newGetRolesForUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func deliverTokenByRPCHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.DeliverTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).DeliverTokenByRPC(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeliverTokenByRPCArgs:
		success, err := handler.(auth.AuthService).DeliverTokenByRPC(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeliverTokenByRPCResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeliverTokenByRPCArgs() interface{} {
	return &DeliverTokenByRPCArgs{}
}

func newDeliverTokenByRPCResult() interface{} {
	return &DeliverTokenByRPCResult{}
}

type DeliverTokenByRPCArgs struct {
	Req *auth.DeliverTokenReq
}

func (p *DeliverTokenByRPCArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.DeliverTokenReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeliverTokenByRPCArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeliverTokenByRPCArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeliverTokenByRPCArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeliverTokenByRPCArgs) Unmarshal(in []byte) error {
	msg := new(auth.DeliverTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeliverTokenByRPCArgs_Req_DEFAULT *auth.DeliverTokenReq

func (p *DeliverTokenByRPCArgs) GetReq() *auth.DeliverTokenReq {
	if !p.IsSetReq() {
		return DeliverTokenByRPCArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeliverTokenByRPCArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeliverTokenByRPCArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeliverTokenByRPCResult struct {
	Success *auth.DeliveryResp
}

var DeliverTokenByRPCResult_Success_DEFAULT *auth.DeliveryResp

func (p *DeliverTokenByRPCResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.DeliveryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeliverTokenByRPCResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeliverTokenByRPCResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeliverTokenByRPCResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeliverTokenByRPCResult) Unmarshal(in []byte) error {
	msg := new(auth.DeliveryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeliverTokenByRPCResult) GetSuccess() *auth.DeliveryResp {
	if !p.IsSetSuccess() {
		return DeliverTokenByRPCResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeliverTokenByRPCResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.DeliveryResp)
}

func (p *DeliverTokenByRPCResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeliverTokenByRPCResult) GetResult() interface{} {
	return p.Success
}

func verifyTokenByRPCHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.VerifyTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).VerifyTokenByRPC(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VerifyTokenByRPCArgs:
		success, err := handler.(auth.AuthService).VerifyTokenByRPC(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VerifyTokenByRPCResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVerifyTokenByRPCArgs() interface{} {
	return &VerifyTokenByRPCArgs{}
}

func newVerifyTokenByRPCResult() interface{} {
	return &VerifyTokenByRPCResult{}
}

type VerifyTokenByRPCArgs struct {
	Req *auth.VerifyTokenReq
}

func (p *VerifyTokenByRPCArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.VerifyTokenReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *VerifyTokenByRPCArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *VerifyTokenByRPCArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *VerifyTokenByRPCArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VerifyTokenByRPCArgs) Unmarshal(in []byte) error {
	msg := new(auth.VerifyTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VerifyTokenByRPCArgs_Req_DEFAULT *auth.VerifyTokenReq

func (p *VerifyTokenByRPCArgs) GetReq() *auth.VerifyTokenReq {
	if !p.IsSetReq() {
		return VerifyTokenByRPCArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VerifyTokenByRPCArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerifyTokenByRPCArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VerifyTokenByRPCResult struct {
	Success *auth.VerifyResp
}

var VerifyTokenByRPCResult_Success_DEFAULT *auth.VerifyResp

func (p *VerifyTokenByRPCResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.VerifyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *VerifyTokenByRPCResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *VerifyTokenByRPCResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *VerifyTokenByRPCResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VerifyTokenByRPCResult) Unmarshal(in []byte) error {
	msg := new(auth.VerifyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VerifyTokenByRPCResult) GetSuccess() *auth.VerifyResp {
	if !p.IsSetSuccess() {
		return VerifyTokenByRPCResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VerifyTokenByRPCResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.VerifyResp)
}

func (p *VerifyTokenByRPCResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyTokenByRPCResult) GetResult() interface{} {
	return p.Success
}

func addPolicyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.PolicyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).AddPolicy(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddPolicyArgs:
		success, err := handler.(auth.AuthService).AddPolicy(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddPolicyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddPolicyArgs() interface{} {
	return &AddPolicyArgs{}
}

func newAddPolicyResult() interface{} {
	return &AddPolicyResult{}
}

type AddPolicyArgs struct {
	Req *auth.PolicyReq
}

func (p *AddPolicyArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.PolicyReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddPolicyArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddPolicyArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddPolicyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddPolicyArgs) Unmarshal(in []byte) error {
	msg := new(auth.PolicyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddPolicyArgs_Req_DEFAULT *auth.PolicyReq

func (p *AddPolicyArgs) GetReq() *auth.PolicyReq {
	if !p.IsSetReq() {
		return AddPolicyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddPolicyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddPolicyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddPolicyResult struct {
	Success *auth.PolicyResp
}

var AddPolicyResult_Success_DEFAULT *auth.PolicyResp

func (p *AddPolicyResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.PolicyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddPolicyResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddPolicyResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddPolicyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddPolicyResult) Unmarshal(in []byte) error {
	msg := new(auth.PolicyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddPolicyResult) GetSuccess() *auth.PolicyResp {
	if !p.IsSetSuccess() {
		return AddPolicyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddPolicyResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.PolicyResp)
}

func (p *AddPolicyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddPolicyResult) GetResult() interface{} {
	return p.Success
}

func removePolicyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.PolicyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).RemovePolicy(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RemovePolicyArgs:
		success, err := handler.(auth.AuthService).RemovePolicy(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RemovePolicyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRemovePolicyArgs() interface{} {
	return &RemovePolicyArgs{}
}

func newRemovePolicyResult() interface{} {
	return &RemovePolicyResult{}
}

type RemovePolicyArgs struct {
	Req *auth.PolicyReq
}

func (p *RemovePolicyArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.PolicyReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RemovePolicyArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RemovePolicyArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RemovePolicyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RemovePolicyArgs) Unmarshal(in []byte) error {
	msg := new(auth.PolicyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RemovePolicyArgs_Req_DEFAULT *auth.PolicyReq

func (p *RemovePolicyArgs) GetReq() *auth.PolicyReq {
	if !p.IsSetReq() {
		return RemovePolicyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RemovePolicyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RemovePolicyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RemovePolicyResult struct {
	Success *auth.PolicyResp
}

var RemovePolicyResult_Success_DEFAULT *auth.PolicyResp

func (p *RemovePolicyResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.PolicyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RemovePolicyResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RemovePolicyResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RemovePolicyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RemovePolicyResult) Unmarshal(in []byte) error {
	msg := new(auth.PolicyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RemovePolicyResult) GetSuccess() *auth.PolicyResp {
	if !p.IsSetSuccess() {
		return RemovePolicyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RemovePolicyResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.PolicyResp)
}

func (p *RemovePolicyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RemovePolicyResult) GetResult() interface{} {
	return p.Success
}

func addRoleForUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.RoleBindingReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).AddRoleForUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddRoleForUserArgs:
		success, err := handler.(auth.AuthService).AddRoleForUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddRoleForUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddRoleForUserArgs() interface{} {
	return &AddRoleForUserArgs{}
}

func newAddRoleForUserResult() interface{} {
	return &AddRoleForUserResult{}
}

type AddRoleForUserArgs struct {
	Req *auth.RoleBindingReq
}

func (p *AddRoleForUserArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.RoleBindingReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddRoleForUserArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddRoleForUserArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddRoleForUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddRoleForUserArgs) Unmarshal(in []byte) error {
	msg := new(auth.RoleBindingReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddRoleForUserArgs_Req_DEFAULT *auth.RoleBindingReq

func (p *AddRoleForUserArgs) GetReq() *auth.RoleBindingReq {
	if !p.IsSetReq() {
		return AddRoleForUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddRoleForUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddRoleForUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddRoleForUserResult struct {
	Success *auth.PolicyResp
}

var AddRoleForUserResult_Success_DEFAULT *auth.PolicyResp

func (p *AddRoleForUserResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.PolicyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddRoleForUserResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddRoleForUserResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddRoleForUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddRoleForUserResult) Unmarshal(in []byte) error {
	msg := new(auth.PolicyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddRoleForUserResult) GetSuccess() *auth.PolicyResp {
	if !p.IsSetSuccess() {
		return AddRoleForUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddRoleForUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.PolicyResp)
}

func (p *AddRoleForUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddRoleForUserResult) GetResult() interface{} {
	return p.Success
}

func removeRoleForUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.RoleBindingReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).RemoveRoleForUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RemoveRoleForUserArgs:
		success, err := handler.(auth.AuthService).RemoveRoleForUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RemoveRoleForUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRemoveRoleForUserArgs() interface{} {
	return &RemoveRoleForUserArgs{}
}

func newRemoveRoleForUserResult() interface{} {
	return &RemoveRoleForUserResult{}
}

type RemoveRoleForUserArgs struct {
	Req *auth.RoleBindingReq
}

func (p *RemoveRoleForUserArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.RoleBindingReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RemoveRoleForUserArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RemoveRoleForUserArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RemoveRoleForUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RemoveRoleForUserArgs) Unmarshal(in []byte) error {
	msg := new(auth.RoleBindingReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RemoveRoleForUserArgs_Req_DEFAULT *auth.RoleBindingReq

func (p *RemoveRoleForUserArgs) GetReq() *auth.RoleBindingReq {
	if !p.IsSetReq() {
		return RemoveRoleForUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RemoveRoleForUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RemoveRoleForUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RemoveRoleForUserResult struct {
	Success *auth.PolicyResp
}

var RemoveRoleForUserResult_Success_DEFAULT *auth.PolicyResp

func (p *RemoveRoleForUserResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.PolicyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RemoveRoleForUserResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RemoveRoleForUserResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RemoveRoleForUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RemoveRoleForUserResult) Unmarshal(in []byte) error {
	msg := new(auth.PolicyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RemoveRoleForUserResult) GetSuccess() *auth.PolicyResp {
	if !p.IsSetSuccess() {
		return RemoveRoleForUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RemoveRoleForUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.PolicyResp)
}

func (p *RemoveRoleForUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RemoveRoleForUserResult) GetResult() interface{} {
	return p.Success
}

func getRolesForUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.RoleQueryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).GetRolesForUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRolesForUserArgs:
		success, err := handler.(auth.AuthService).GetRolesForUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRolesForUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRolesForUserArgs() interface{} {
	return &GetRolesForUserArgs{}
}

func newGetRolesForUserResult() interface{} {
	return &GetRolesForUserResult{}
}

type GetRolesForUserArgs struct {
	Req *auth.RoleQueryReq
}

func (p *GetRolesForUserArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(auth.RoleQueryReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetRolesForUserArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetRolesForUserArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetRolesForUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRolesForUserArgs) Unmarshal(in []byte) error {
	msg := new(auth.RoleQueryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRolesForUserArgs_Req_DEFAULT *auth.RoleQueryReq

func (p *GetRolesForUserArgs) GetReq() *auth.RoleQueryReq {
	if !p.IsSetReq() {
		return GetRolesForUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRolesForUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRolesForUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRolesForUserResult struct {
	Success *auth.RoleQueryResp
}

var GetRolesForUserResult_Success_DEFAULT *auth.RoleQueryResp

func (p *GetRolesForUserResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(auth.RoleQueryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetRolesForUserResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetRolesForUserResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetRolesForUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRolesForUserResult) Unmarshal(in []byte) error {
	msg := new(auth.RoleQueryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRolesForUserResult) GetSuccess() *auth.RoleQueryResp {
	if !p.IsSetSuccess() {
		return GetRolesForUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRolesForUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.RoleQueryResp)
}

func (p *GetRolesForUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRolesForUserResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DeliverTokenByRPC(ctx context.Context, Req *auth.DeliverTokenReq) (r *auth.DeliveryResp, err error) {
	var _args DeliverTokenByRPCArgs
	_args.Req = Req
	var _result DeliverTokenByRPCResult
	if err = p.c.Call(ctx, "DeliverTokenByRPC", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyTokenByRPC(ctx context.Context, Req *auth.VerifyTokenReq) (r *auth.VerifyResp, err error) {
	var _args VerifyTokenByRPCArgs
	_args.Req = Req
	var _result VerifyTokenByRPCResult
	if err = p.c.Call(ctx, "VerifyTokenByRPC", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddPolicy(ctx context.Context, Req *auth.PolicyReq) (r *auth.PolicyResp, err error) {
	var _args AddPolicyArgs
	_args.Req = Req
	var _result AddPolicyResult
	if err = p.c.Call(ctx, "AddPolicy", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemovePolicy(ctx context.Context, Req *auth.PolicyReq) (r *auth.PolicyResp, err error) {
	var _args RemovePolicyArgs
	_args.Req = Req
	var _result RemovePolicyResult
	if err = p.c.Call(ctx, "RemovePolicy", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddRoleForUser(ctx context.Context, Req *auth.RoleBindingReq) (r *auth.PolicyResp, err error) {
	var _args AddRoleForUserArgs
	_args.Req = Req
	var _result AddRoleForUserResult
	if err = p.c.Call(ctx, "AddRoleForUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveRoleForUser(ctx context.Context, Req *auth.RoleBindingReq) (r *auth.PolicyResp, err error) {
	var _args RemoveRoleForUserArgs
	_args.Req = Req
	var _result RemoveRoleForUserResult
	if err = p.c.Call(ctx, "RemoveRoleForUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRolesForUser(ctx context.Context, Req *auth.RoleQueryReq) (r *auth.RoleQueryResp, err error) {
	var _args GetRolesForUserArgs
	_args.Req = Req
	var _result GetRolesForUserResult
	if err = p.c.Call(ctx, "GetRolesForUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
